language: elixir

elixir:
  - '1.8.2'

otp_release: '21.3'

services:
  - postgresql

matrix:
  include:
    - env: 'travis'

before_script:
  - mix dialyzer
  - cd apps/hefty && export MIX_ENV=test && mix ecto.reset